default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: localhost
  port: 5432

development:
  <<: *default
  database: podcast

test:
  <<: *default
  database: podcast_test

production:
  <<: *default
  database: podcast_pro